# Copyright (C) 2026 Luca Palmieri
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of sif. See COPYING for the full license text.

"""Build the API reference tree from the contents of ``include/sif``.

One page per public header, grouped into one directory per subsystem. The
pages are written before Sphinx reads the source tree and are not committed:
adding a header adds a page, deleting one deletes it, and there is nothing to
keep in step by hand.

The shape is the point. A page per subsystem puts every function of every
header into one "on this page" panel -- for ``structures`` that was some
hundreds of entries, counting struct members -- while a page per header gives
the left-hand tree a level to collapse and leaves each page's panel short
enough to read.
"""

from pathlib import Path

# Subsystem directory -> (title, one-line description). A directory that turns
# up in include/sif without an entry here still gets a page, titled after
# itself, so a new subsystem is never silently dropped from the site.
SUBSYSTEMS = {
    "core": ("Core", "Types, option flags, status codes and the library lifecycle."),
    "structures": ("Structures", "The containers the rest of the library is built on."),
    "finder": ("Finders", "Void finders."),
    "measure": ("Measurements", "Quantities computed from a catalogue or a field."),
    "model": ("Models", "Analytic and semi-analytic predictions."),
    "io": ("Input and output", "Reading and writing sif's on-disk formats."),
    "utils": ("Utilities", "Allocation, sorting, logging, timing and the rest."),
}

# Order the subsystems are listed in: roughly the order a reader meets them,
# rather than alphabetically. Anything not named here follows, sorted.
ORDER = ["core", "structures", "finder", "measure", "model", "io", "utils"]

GENERATED_NOTE = (
    "<!-- Generated by docs/_ext/apitree.py. Edits here are overwritten on the\n"
    "     next build; change the header's comments instead. -->\n"
)


def _sorted_subsystems(include_root):
    found = sorted(p.name for p in include_root.iterdir() if p.is_dir())
    ranked = [s for s in ORDER if s in found]
    return ranked + [s for s in found if s not in ranked]


def _write(path, text):
    """Write only on change, so an unchanged page does not force a rebuild."""
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)


def generate(app):
    include_root = Path(app.config.hawkmoth_root) / "sif"
    api_root = Path(app.srcdir) / "api"

    if not include_root.is_dir():
        raise FileNotFoundError(f"no headers under {include_root}")

    subsystems = _sorted_subsystems(include_root)

    for sub in subsystems:
        title, blurb = SUBSYSTEMS.get(sub, (sub.replace("_", " ").title(), ""))
        out_dir = api_root / sub
        out_dir.mkdir(parents=True, exist_ok=True)

        headers = sorted(p.name for p in (include_root / sub).glob("*.h"))
        stale = {p.name for p in out_dir.glob("*.md")} - {"index.md"}

        for header in headers:
            stem = header[:-2]
            stale.discard(f"{stem}.md")

            # Hawkmoth emits reStructuredText, so the directive has to reach
            # the reST parser: MyST would otherwise pass the generated source
            # through as literal text.
            # Titled by the file alone: the page already sits under its
            # subsystem in the tree, and the full path is long enough to be
            # truncated there. The include line carries it instead, where it
            # is the thing a reader actually wants to copy.
            _write(
                out_dir / f"{stem}.md",
                f"{GENERATED_NOTE}\n"
                f"# `{header}`\n\n"
                "```c\n"
                f"#include <sif/{sub}/{header}>\n"
                "```\n\n"
                "```{eval-rst}\n"
                f".. c:autodoc:: sif/{sub}/{header}\n"
                "```\n",
            )

        # A header that was deleted or renamed must not leave its page behind,
        # or the site keeps documenting an API that no longer exists.
        for orphan in stale:
            (out_dir / orphan).unlink()

        entries = "\n".join(h[:-2] for h in headers)
        _write(
            out_dir / "index.md",
            f"{GENERATED_NOTE}\n"
            f"# {title}\n\n"
            f"{blurb}\n\n"
            "```{toctree}\n"
            ":maxdepth: 1\n\n"
            f"{entries}\n"
            "```\n",
        )

    app.env.note_dependency(str(include_root))


def setup(app):
    app.connect("builder-inited", generate)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
