# Copyright (C) 2026 Luca Palmieri
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of sif. See COPYING for the full license text.

"""Build the Python API reference tree by discovering ``pysif`` submodules.

Mirrors what ``apitree.py`` does for the C headers: one page per submodule,
generated at build time so adding a submodule adds a page, and there is
nothing to keep in step by hand.

The root module (``pysif``) gets its own page for the library lifecycle
functions (``init``, ``finalize``, ``set_setting``, ``get_setting``) and the
data-structure types (``Field``, ``Grid``, ``Catalog``, ...) that live at the
package level.
"""

from pathlib import Path

# Submodule name -> (title, one-line description). The root module is handled
# separately. A submodule that turns up at runtime without an entry here still
# gets a page, titled after itself.
SUBMODULES = {
    "finders": ("Finders", "Void finders."),
    "io": ("Input and output", "Reading and writing sif's on-disk formats."),
    "measure": ("Measurements", "Quantities computed from a catalogue or a field."),
    "model": ("Models", "Analytic and semi-analytic predictions."),
}

# Order submodules are listed in, matching the C API order.
ORDER = ["finders", "measure", "model", "io"]

GENERATED_NOTE = (
    "<!-- Generated by docs/_ext/pytree.py. Edits here are overwritten on the\n"
    "     next build; change the module's docstrings instead. -->\n"
)


def _write(path, text):
    """Write only on change, so an unchanged page does not force a rebuild."""
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)


def _discover_submodules():
    """Return the submodules pysif exposes, in the preferred order."""
    try:
        import pysif
    except ImportError:
        # pysif is not installed -- fall back to the static table.
        return list(ORDER)

    found = []
    for name in dir(pysif):
        obj = getattr(pysif, name)
        if hasattr(obj, "__name__") and getattr(obj, "__name__", "").startswith("pysif."):
            subname = obj.__name__.split(".", 1)[1]
            if subname not in found:
                found.append(subname)

    # Impose the preferred order, then append anything new.
    ranked = [s for s in ORDER if s in found]
    extras = [s for s in found if s not in ranked]
    return ranked + sorted(extras) if found else list(ORDER)


def generate(app):
    py_root = Path(app.srcdir) / "python"
    py_root.mkdir(parents=True, exist_ok=True)

    submodules = _discover_submodules()

    # --- One page per submodule -------------------------------------------
    stale = {p.name for p in py_root.glob("*.md")} - {"index.md"}

    for sub in submodules:
        title, blurb = SUBMODULES.get(sub, (sub.replace("_", " ").title(), ""))
        stale.discard(f"{sub}.md")

        _write(
            py_root / f"{sub}.md",
            f"{GENERATED_NOTE}\n"
            f"# `pysif.{sub}`\n\n"
            f"{blurb}\n\n"
            "```{eval-rst}\n"
            f".. automodule:: pysif.{sub}\n"
            "   :members:\n"
            "   :undoc-members:\n"
            "```\n",
        )

    # The root page documents pysif itself: init/finalize + the types.
    stale.discard("pysif.md")
    _write(
        py_root / "pysif.md",
        f"{GENERATED_NOTE}\n"
        "# `pysif`\n\n"
        "Library lifecycle and data structures.\n\n"
        "```{eval-rst}\n"
        ".. automodule:: pysif\n"
        "   :members:\n"
        "   :undoc-members:\n"
        "```\n",
    )

    # Clean up pages for submodules that no longer exist.
    for orphan in stale:
        (py_root / orphan).unlink()

    # --- Index ------------------------------------------------------------
    entries = "pysif\n" + "\n".join(submodules)
    _write(
        py_root / "index.md",
        f"{GENERATED_NOTE}\n"
        "# Python API Reference\n\n"
        "Auto-generated from the ``pysif`` module docstrings.\n\n"
        "The data structures -- ``Field``, ``Grid``, ``Catalog`` and the rest "
        "-- live at the package root (``pysif.Field``), and the operations on "
        "them are grouped into submodules.\n\n"
        "```{toctree}\n"
        ":maxdepth: 1\n\n"
        f"{entries}\n"
        "```\n",
    )


def setup(app):
    app.connect("builder-inited", generate)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
