# Copyright (C) 2026 Luca Palmieri
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of sif. See COPYING for the full license text.

name: sif-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy>=1.20
  - scikit-build-core
  - cmake>=3.15
  - ninja
  - c-compiler
  - fftw
  - llvm-openmp