# Copyright (C) 2026 Luca Palmieri
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of sif. See COPYING for the full license text.

"""Sphinx configuration for the sif documentation.

The C API is not generated by Doxygen. Hawkmoth parses the public headers
directly with libclang and emits native Sphinx C-domain directives, so the
reference pages carry the same theme, the same navigation and the same search
index as the prose. See docs/api/index.md for what that means when writing
comments in the headers.
"""

import os
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

sys.path.insert(0, str(Path(__file__).parent / "_ext"))

# --- libclang --------------------------------------------------------------

# Hawkmoth reaches libclang through the Python bindings, which find it on their
# own: the pinned `libclang` wheel ships a copy, and that is what CI loads. The
# override below is only for a local install that needs pointing elsewhere --
# Homebrew LLVM on macOS, or whatever SIF_LIBCLANG_PATH names.
#
# It has to stay conditional. set_library_path() does not check the directory,
# it just makes the bindings look there and nowhere else, so naming a path that
# does not exist on the machine doing the build turns every autodoc into a
# LibclangError -- which is how a hard-coded Homebrew path once broke the
# Linux CI job while every local build stayed green.
LIBCLANG_PATHS = [os.environ.get("SIF_LIBCLANG_PATH"), "/opt/homebrew/opt/llvm/lib"]

for _path in filter(None, LIBCLANG_PATHS):
    if Path(_path).is_dir():
        from clang.cindex import Config

        Config.set_library_path(_path)
        break

# --- Project ---------------------------------------------------------------

project = "sif"
author = "Luca Palmieri"
copyright = "2026, Luca Palmieri"

# Kept in step with CMakeLists.txt by hand for now; wire it up once the docs
# build is part of the same pipeline.
version = "0.1"
release = "0.1.0"

# --- Sources ---------------------------------------------------------------

extensions = [
    "myst_parser",  # prose in Markdown rather than reStructuredText
    "hawkmoth",  # C API straight from the headers
    "hawkmoth.ext.javadoc",  # ... written in @brief / @param style
    "sphinx.ext.autodoc",  # Python API from pysif's docstrings
    "sphinx.ext.napoleon",  # ... written in Google style (Args:, Returns:)
    "sphinx.ext.intersphinx",
    "apitree",  # one API page per header, generated from include/sif
    "pytree",  # one API page per submodule, generated from pysif
    "sphinx_design"
]

source_suffix = {".md": "markdown", ".rst": "restructuredtext"}

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The headers use single backticks for identifiers and short expressions, which
# reStructuredText would otherwise render as title references in italics. This
# makes them literals, so a comment reads the same in the source and on the
# page -- and, because interpreted text is not scanned for markup, it is also
# what lets `|delta|` keep its bars.
default_role = "code"

# --- Hawkmoth --------------------------------------------------------------

# Paths in a `c:autodoc` directive are resolved against this, so an API page
# names a header exactly as a caller would include it.
hawkmoth_root = str(REPO / "include")

hawkmoth_clang = [
    f"-I{REPO / 'include'}",
    "-std=gnu99",
]

# Which compiler hawkmoth asks for the system include paths.
#
# hawkmoth_autoconf defaults to ['stdinc'], so hawkmoth runs `<compiler> -E
# -Wp,-v` and passes what it finds to libclang as `-nostdinc -isystem...`.
# libclang itself ships no headers -- the `libclang` wheel is the bare library
# -- so those paths are the only ones there are.
#
# The default compiler name is 'clang'. When it is not on PATH the helper still
# emits the -nostdinc, with no -isystem after it: the search path ends up empty
# and every header in include/sif fails on its first #include, none of the
# errors mentioning a compiler. The CI image is Debian with gcc and no clang,
# which is exactly that case, so the name is looked up rather than assumed.
# clang comes first because libclang is what does the parsing.
HAWKMOTH_COMPILERS = ["clang", "gcc", "cc"]

hawkmoth_compiler = next((cc for cc in HAWKMOTH_COMPILERS if shutil.which(cc)), None)

if hawkmoth_compiler is None:
    raise RuntimeError(
        "no C compiler found on PATH (tried: "
        + ", ".join(HAWKMOTH_COMPILERS)
        + "). Hawkmoth needs one to resolve <stdint.h> and friends; without it "
        "every API page fails with a file-not-found that does not say so."
    )

# The headers are commented in Doxygen style, so every comment goes through the
# javadoc transform on its way to reStructuredText.
hawkmoth_transform_default = "javadoc"

# --- MyST ------------------------------------------------------------------

myst_enable_extensions = [
    "colon_fence",  # ::: fences, which survive being pasted into GitHub
    "deflist",
    "dollarmath",  # $...$ and $$...$$
    "attrs_inline",
]

myst_heading_anchors = 3

# --- HTML ------------------------------------------------------------------

html_theme = "shibuya"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_title = "sif"

# A struct member is not a place on the page worth navigating to, and with one
# page per header the functions are a short list rather than a wall. Kept on so
# the panel is useful; the tree stays readable because the pages are small.
toc_object_entries_show_parents = "hide"

html_theme_options = {
    "accent_color": "indigo",
    "globaltoc_expand_depth": 1,
    "github_url": "https://github.com/lucapalmi/sif",
}

# --- Cross-project links ---------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
}
