/* Copyright (C) 2026 Luca Palmieri
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of sif. See COPYING for the full license text.
 */

/**
 * @file sort.h
 * @brief Type-specialized quicksort, generated by macro.
 *
 * Generated rather than passed a comparison function pointer: these sorts run
 * on arrays of millions of scalars, where an indirect call per comparison
 * costs more than the comparison, and inlining the predicate is what lets the
 * partition loop stay in registers.
 */

#ifndef SIF_UTILS_SORT_H
#define SIF_UTILS_SORT_H

#include <stdint.h>

/**
 * @brief Define a quicksort over @p type at file scope.
 *
 * Expands to a pair of `static` functions: the entry point @p function_name,
 * taking `(type* arr, uint64_t count)`, and its recursive helper. Place it at
 * file scope in a `.c`, once per (type, order) pair needed:
 *
 * @code
 * SIF_DEFINE_QUICKSORT(sort_radii_desc, sif_real, a > b)
 * SIF_DEFINE_QUICKSORT(sort_real_asc,   sif_real, a < b)
 * ...
 * sort_radii_desc(radii, n);
 * @endcode
 *
 * @param function_name Name of the generated entry point.
 * @param type Element type, sorted by value.
 * @param less_than_expr Ordering predicate, written in terms of **two
 * variables named `a` and `b`** that the macro declares for you. It must be a
 * strict weak ordering: `a < b` for ascending, `a > b` for descending.
 *
 * @note The predicate is evaluated twice per element, once as given and once
 * with the operands exchanged, to obtain both "less" and "greater" from a
 * single expression. This is what makes the partition three-way, so runs of
 * equal keys are placed in one pass instead of being repeatedly re-partitioned
 * -- the right trade for radius arrays, which are full of ties.
 *
 * @warning Recursion is not depth-limited and the larger partition is not
 * eliminated by a tail call, so a pathological input costs stack proportional
 * to the element count. The pivot is the middle element, which makes sorted
 * and reverse-sorted input the good case rather than the bad one, but an
 * adversarial ordering is not defended against.
 */
#define SIF_DEFINE_QUICKSORT(function_name, type, less_than_expr)              \
  static void function_name##_recursive(                                       \
    type* arr, int64_t low, int64_t high) {                                    \
    if (low >= high)                                                           \
      return;                                                                  \
    int64_t lt = low, gt = high;                                               \
    type pivot = arr[low + (high - low) / 2];                                  \
    int64_t i = low;                                                           \
    while (i <= gt) {                                                          \
      type a = arr[i], b = pivot;                                              \
      uint8_t is_less = (less_than_expr);                                      \
      a = pivot;                                                               \
      b = arr[i];                                                              \
      uint8_t is_greater = (less_than_expr);                                   \
      if (is_less) {                                                           \
        type temp = arr[lt];                                                   \
        arr[lt] = arr[i];                                                      \
        arr[i] = temp;                                                         \
        lt++;                                                                  \
        i++;                                                                   \
      } else if (is_greater) {                                                 \
        type temp = arr[i];                                                    \
        arr[i] = arr[gt];                                                      \
        arr[gt] = temp;                                                        \
        gt--;                                                                  \
      } else {                                                                 \
        i++;                                                                   \
      }                                                                        \
    }                                                                          \
    function_name##_recursive(arr, low, lt - 1);                               \
    function_name##_recursive(arr, gt + 1, high);                              \
  }                                                                            \
  static inline void function_name(type* arr, uint64_t count) {                \
    if (count > 1) {                                                           \
      function_name##_recursive(arr, 0, (int64_t)count - 1);                   \
    }                                                                          \
  }

#endif /* SIF_UTILS_SORT_H */
